- name: Getting data from routers

  hosts: routers
  
  gather_facts: false

  tasks:

    - name: system command

      routeros_command:

        commands: /ip route export

      register: system_print

    - name: debug print

      debug: var=system_print.stdout_lines
