- name: Getting data from routers

  hosts: routers

  gather_facts: false

  tasks:

    - name: system command

      routeros_command:

        commands:
         [
          '/user set admin password=new_password',
         ]

      register: system_print

    - name: debug print

      debug: var=system_print.stdout_lines
